import React, { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { FiTrendingUp, FiTarget, FiAlertCircle, FiBookOpen, FiArrowRight } from 'react-icons/fi';

const ResultsPage = () => {
  const { state } = useLocation();
  const navigate = useNavigate();
  const [feedback, setFeedback] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const getFeedback = async () => {
      // If someone refreshes the page, state is lost. Redirect them.
      if (!state) {
        navigate('/');
        return;
      }

      try {
        const res = await fetch('http://localhost:5000/api/generate-feedback', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            quizData: state.quizData,
            userAnswers: state.userAnswers,
            topic: state.topic || "General Quiz"
          })
        });
        
        if (!res.ok) throw new Error("Server error");
        
        const data = await res.json();
        setFeedback(data);
      } catch (err) {
        console.error("Feedback error:", err);
        // Set fallback data so UI doesn't break
        setFeedback({
          laggingConcepts: ["Connection lost"],
          areasToImprove: ["Please check your internet"],
          actionPlan: ["Retry from dashboard"],
          overallPerformance: "We couldn't reach the AI tutor.",
          encouragement: "Don't worry, your score was still saved!"
        });
      } finally {
        setLoading(false);
      }
    };

    getFeedback();
  }, [state, navigate]);

  if (loading) return (
    <div className="min-h-screen bg-black text-white flex flex-col items-center justify-center">
      <div className="w-12 h-12 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mb-4"></div>
      <p className="animate-pulse font-bold tracking-widest text-zinc-500">AI ANALYZING PERFORMANCE...</p>
    </div>
  );

  return (
    <div className="min-h-screen bg-[#050505] text-zinc-300 p-8">
      <div className="max-w-4xl mx-auto">
        <header className="mb-12 text-center">
          <h1 className="text-4xl font-black text-white mb-2 tracking-tighter">Performance Analytics</h1>
          <p className="text-zinc-500 uppercase tracking-[0.3em] text-[10px] font-bold">Generated by Quizzfy AI</p>
        </header>

        <div className="grid md:grid-cols-3 gap-6 mb-10">
          <FeedbackCard 
            title="Lagging Concepts" 
            items={feedback?.laggingConcepts || []} 
            icon={<FiAlertCircle className="text-red-400"/>} 
            color="border-red-500/20"
          />
          <FeedbackCard 
            title="Areas to Improve" 
            items={feedback?.areasToImprove || []} 
            icon={<FiTarget className="text-yellow-400"/>} 
            color="border-yellow-500/20"
          />
          <FeedbackCard 
            title="Study Roadmap" 
            items={feedback?.actionPlan || feedback?.studyRoadmap || []} 
            icon={<FiTrendingUp className="text-blue-400"/>} 
            color="border-blue-500/20"
          />
        </div>

        <div className="bg-zinc-900/30 border border-zinc-800 p-8 rounded-[32px] mb-10 shadow-2xl">
          <h3 className="flex items-center gap-2 text-white font-bold mb-4">
            <FiBookOpen className="text-blue-500" /> AI Diagnostic Summary
          </h3>
          <p className="text-zinc-400 leading-relaxed italic text-lg">
            "{feedback?.overallPerformance || "Analysis complete."}"
          </p>
          <div className="mt-8 p-5 bg-emerald-500/5 border border-emerald-500/10 rounded-2xl text-emerald-500 text-sm font-medium">
            {feedback?.encouragement}
          </div>
        </div>

        <button 
          onClick={() => navigate('/')}
          className="w-full py-5 bg-zinc-900 hover:bg-white hover:text-black text-white font-bold rounded-2xl border border-zinc-800 transition-all flex items-center justify-center gap-3 active:scale-95"
        >
          Return to Dashboard <FiArrowRight size={20}/>
        </button>
      </div>
    </div>
  );
};

const FeedbackCard = ({ title, items, icon, color }) => (
  <div className={`bg-[#0a0a0a] border ${color} p-7 rounded-[28px] hover:bg-zinc-900/40 transition-colors`}>
    <div className="flex items-center gap-3 mb-6">
      <div className="p-2 bg-zinc-900 rounded-lg">{icon}</div>
      <h3 className="text-[10px] font-black uppercase text-zinc-500 tracking-widest">{title}</h3>
    </div>
    <ul className="space-y-4">
      {items.length > 0 ? items.map((item, i) => (
        <li key={i} className="text-xs text-zinc-400 flex gap-3 leading-relaxed">
          <span className="text-blue-500 font-bold">•</span> {item}
        </li>
      )) : (
        <li className="text-xs text-zinc-600 italic">No data available</li>
      )}
    </ul>
  </div>
);

export default ResultsPage;